# -*- coding: utf-8 -*-
"""PythonQ3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhXANe9GEr8NP4tklQFSpzp4COTPizcI
"""

try :
  name = input("Please enter the students name ")
  mark1 = int(input("Please enter the marks of subject 1 "))
  mark2 = int(input("Please enter the marks of subject 2 "))
  mark3 = int(input("Please enter the marks of subject 3 "))
  if 0<= mark1 <= 100 and 0<= mark2 <= 100 and 0<= mark3 <= 100 :
    total = mark1 + mark2 + mark3
    print(f"Total marks : {total}")
    Average = total/3
    print(f"Average marks : {Average:.2f}")
    if Average >= 90 :
      print("Grade : A")
    elif Average >= 80 :
      print("Grade : B")
    elif Average >= 70 :
      print("Grade : C")
    elif Avergae >= 60 :
      print("Grade : D")
    else :
      print("Grade : F")
  else :
    print("Please enter marks between 0 and 100")
except :
  print("Please enter the information in the correct data type")