# -*- coding: utf-8 -*-
"""PythonQ8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhXANe9GEr8NP4tklQFSpzp4COTPizcI
"""

n = []
x = int(input("Please enter how many numbers you want to enter into the list: "))
for i in range(x):
    number = int(input("Enter the number: "))
    n.append(number)
oddvalue = {}
for i in range(x):
    if n[i] % 2 != 0:
        oddvalue[n[i]] = n[i] ** 3
for key, value in oddvalue.items():
    print(key, ":", value)