# -*- coding: utf-8 -*-
"""pythonq7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rs_N3X4bUkHwHEEMfQQ9pVsq7xcP4Ynz
"""

def callfile(filename) :
  with open(filename,"r") as file :
    line = file.readlines()

  purchased = {}
  free = {}
  discount = {}

  for i in line :
    i = i.strip()
    word = i.split()
    if "Discount " in i :
      discount["Amount"] = int(word[1])
    elif "Free" in i :
      item = word[0]
      free[item] = 0
    else :
      item = word[0]
      purchased[item] = int(word[-1])
total = len(purchased)
freeitems = len(free)
amount = sum(purchased.values())
discount1 = int(dicount["Amount"])
finalvalue = amount - discount1

print(f"Total number of items purchased : {total}")
print(f"Number of free items : {freeitems}")
print(f"Total amount to pay : {amount}")
print(f"Discount given : {discount1}")
print(f"Final amount after discount : {finalvalue} ")

callfile("purchase-1.txt")