# -*- coding: utf-8 -*-
"""pythonqpp2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fEi95bUcuCedTizo2eLLleh3sXHkHc10
"""

from math_utils import factorial, is_prime, gcd
n = input("Please insert a number to calculate factorial and check if its prime")
factorial(n)
is_prime(n)
x = input("Please input first number to check GCD")
y = input("Please input second number to check GCD")
gcd(x,y)

pip install pythonq5