# -*- coding: utf-8 -*-
"""PythonQ2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhXANe9GEr8NP4tklQFSpzp4COTPizcI
"""

costph = 0.51
# Cost per Day
costpd = costph* 24
print(f"Cost per day: {costpd}")
# Cost per Week
costpw = costpd * 7
print(f"Cost per week: ${costpw}")
# Cost per month
costpm = costpw * 30
print(f"Cost per month: ${costpm}")
# Days with $918
timepw = 918/(0.51*24)
print(f"With $918, you can operate for {timepw} days")