# -*- coding: utf-8 -*-
"""PythonQ1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhXANe9GEr8NP4tklQFSpzp4COTPizcI
"""

distance = int(input("How far do you want to travel (in miles)? "))

if distance < 3:
    print("You should ride a Bicycle.")
elif distance>=3 and distance < 300:
    print("You should ride a Motor-Cycle.")
else:
    print("You should drive a Super-Car.")