# -*- coding: utf-8 -*-
"""PythonQ6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhXANe9GEr8NP4tklQFSpzp4COTPizcI
"""

employee = []
print("Please enter employee details and enter stop to finish")
while True:
    name = input("Enter employee name: ")
    if name == "stop":
        break
    try:
        bsalary = int(input("Enter basic salary: "))
        hra = bsalary*0.20
        da = bsalary*0.10
        tsalary = bsalary+hra+da
        employee.append({
            'name': name,
            'basic salary': bsalary,
            'total salary': tsalary
        })
    except ValueError:
        print("Error: Please enter a valid salary!")
print("Employee report")
for i in employee:
    print(f"Employee: {i['name']}")
    print(f"Basic Salary: {i['basic salary']:.2f}")
    print(f"Total Salary: {i['total
    salary']:.2f}")