# -*- coding: utf-8 -*-
"""PythonQ8-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhXANe9GEr8NP4tklQFSpzp4COTPizcI
"""

x = int(input("Please enter how many numbers you want to enter into the list: "))
n = [int(input("Enter the number: ")) for i in range(x)]
oddvalue = {num: num**3 for num in n if num % 2 != 0}
for x,y in oddvalue.items():
    print(x, ":", y)